// <auto-generated />
namespace Garage3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class validering_regnr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validering_regnr));
        
        string IMigrationMetadata.Id
        {
            get { return "201612060915468_validering_regnr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
